server:
  port: 8082
build:
  version: 1.2

spring:
  application:
    name: card-service
  datasource:
    url: jdbc:h2:mem:testdb:DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
